### ISSUE TITLE
Investigate Slack API

### ISSUE THREAD

**Issue by nikymorg** [flatiron-school/flombot#1]
- how does bot listen in a channel
- what endpoints are we hitting on Slack API
- what is auth flow for Slack
- who can invite bot into a channel

**Comment by TezSmith** [comment]
**How does a bot listen in a channel?**

Once a Bot User is created for a Slack Channel, it can listen in to user convos / actions through the Events API. Depending on configuration, a bot can be "told" to listen into a conversation when it is mentioned (Ex. Hey @jokebot - Can you tell me a joke?) through the app_mention event type, or a bot can respond to certain pre-defined word or phase through the message event type.

`//Sample code from Slack Handling Events Page https://api.slack.com/bot-users#handling-events
router.post("/", function(req, res, next) {
    let payload = req.body;
    res.sendStatus(200);
    if (payload.event.type === "app_mention") {
        if (payload.event.text.includes("tell me a joke")) {
            // Make call to chat.postMessage using bot's token
        }
    }
    if (payload.event.type === "message") {
        let response_text;
        if (payload.event.text.includes("Who's there?")) {
            response_text = "A bot user";
        }
    }
}`
 ** Slackbot uses Node.js & Express

**What endpoints are we hitting?** 

The main endpoint I can detect is _https://slack.com/api/chat.postMessage_. This endpoint allows our bot to send a message to our channel based on the event type that called the bot. See sample code above.

**Comment by matt-mcalister** [comment]
### Auth Flow:
It seems there are two pieces of Auth that need to be considered:
		1. Obtaining the tokens. 
			* Obtained through the workspace admin dashboard in the app's settings under `Install App > Bot User OAuth Access Token` in the [app’s settings page](https://api.slack.com/apps).
			* Bot tokens can also be generated using the [OAuth install flow](https://api.slack.com/docs/oauth#bots) if you are distributing your app beyond your own workspace. `NOTE: I don’t think this would be part of MVP, if we were ever interested in doing this. We should go with just grabbing the tokens from the app dashboard.`
		2. Authenticating the messages we want the bot to send to the workspace (or any other actions we want to make concerning the bot itself).
			* We’ll simply include our token with the key of `”token”` at the top level of our JSON payload we send to the server, every time.
Full resources: [Using OAuth 2.0 | Slack](https://api.slack.com/docs/oauth)

### Who can invite bot into a channel
It does not appear that apps and bots have built in permissions functionalities around who can/cannot invite the bot into a channel. However, here are some alternative ideas:
	* We can easily ensure that the bot doesn’t respond to private channels (ie it will only listen in public channels). Keeping in mind that students can’t create private channels, this could help with curbing karma farming, etc.
	* We can use the slack RTM api (which involves connecting to the Slack web sockets to respond in realtime) to listen for when the bot joins a channel, use that event’s information to see which user invited them (and if they’re an admin), then force the bot to leave the channel if they were not invited by an admin. `NOTE: this would be kind of janky, because it does not actually prevent the bot from joining the channel, it simply makes it so that a user adds the bot, then the bot immediately leaves. This would also involve using the RTM API, which would only be a separate API (and request/response cycle) for a single feature.`

**Comment by nikymorg** [comment]
Great research and thoughts about future expandability. We'll decide next steps async over Slack next week.

![image](https://user-images.githubusercontent.com/20468684/48677320-202cab00-eb41-11e8-9c0b-490521d8230f.png)
