### ISSUE TITLE
Investigate Slack endpoints

### ISSUE THREAD

**Issue by nikymorg** [flatiron-school/flombot#6]
- which endpoints are relevant for our purpose
- what information do they require
- what information do they return

**Comment by mmacdonald1** [comment]
So we have found 3 endpoints that we will need depending on how we choose to build the bot: app_mention (Event API), message (Event API), chat.postMessage (Web API).  

We have two major events (giving tacos and messages and posting the tacos and messages).
Giving a taco message could use one of two options:
1. Melanie says "@taco-app @will is the best :taco:"
This triggers an "app_mention" event (that we have set up), which sends us a JSON payload. We answer with a status of 200 and parse the payload and add it to our database.

2. Melanie says "@will is the best :taco:"
We read every "message" event parse it for :taco: and username. We answer with a status of 200. If the JSON payload text contains those parameters, we parse the information and store in our database. Else, we do nothing.

Giving a taco summary:
Send a post request to the chat.postMessage endpoint with our formatted table data.

**Comment by mmacdonald1** [comment]
Example app-mention logic:
`router.post("/", function(req, res, next) {
    let payload = req.body;
    res.sendStatus(200);

    if (payload.event.type === "app_mention") {
        if (payload.event.text.includes("tell me a joke")) {
            // Make call to chat.postMessage using bot's token
        }
    }
}`

**Comment by mmacdonald1** [comment]
Example chat.postMessage
`
POST https://slack.com/api/chat.postMessage
Content-type: application/json
Authorization: Bearer YOUR_BOTS_TOKEN
{
    "text": "Hello <@UA8RXUPSP>! Knock, knock.",
    "channel": "CBR2V3XEX"
}
`

**Comment by mmacdonald1** [comment]
In the end our two physical end points are "/" and "https://slack.com/api/chat.postMessage", but we need to set up events for the message data (app_mention or message).

**Comment by will** [comment]
> Melanie says "@will is the best 🌮" 

Aww thanks 😇

**Comment by wley3337** [comment]
For our listening end point I think that the "/" is going to be our "/REGISTERED_BOT_URL" and then we'll need to look in the JSON for "type": "SOME_KIND_OF_ACTION" to respond to, kind of like redux.
