### ISSUE TITLE
Investigate gems or other tools for integration

### ISSUE THREAD

**Issue by nikymorg** [flatiron-school/flombot#7]
- are they worth it
- can we duplicate that functionality ourselves
- what can we learn from them

**Comment by SamCatherman** [comment]
https://rubygems.org/gems/slack-api/versions/1.2.3
(https://github.com/aki017/slack-ruby-gem)
https://github.com/slack-ruby/slack-ruby-client
https://github.com/stevenosloan/slack-notifier

Did some googling today, these all look like they could be helpful!

**Comment by nikymorg** [comment]
Do you have a suggestion about which one we should use? Are all still being actively maintained. Are any more popular than the others? Do they all handle equivalent things or do any of them handle something extra for us, like auth?

**Comment by morgvanny** [comment]
Those appear to be ordered from least to most popular.

As far as maintenance goes, slack-ruby-client was last updated a few weeks ago, while slack-notifier was last updated 2 months ago, and slack-ruby-gem (least popular) was last updated in May.

slack-ruby-client's documentation says 

> If you're trying to build a Real Time bot, use slack-ruby-bot, which uses this library.

then slack-ruby-bot's documentations says

> If you're trying to roll out a full service with Slack button integration, check out slack-ruby-bot-server, which uses this library.

Starting to feel a bit rabbit-holey but that's found [here](https://github.com/slack-ruby/slack-ruby-bot-server) and while it doesn't seem necessarily hugely popular, it seems pretty nice, and maintained. It could possibly do a lot more work for us.

**Comment by SamCatherman** [comment]
++, was just about to share [slack-ruby-bot-server](https://github.com/slack-ruby/slack-ruby-bot-server)! There are a ton of other repos under 'slack-ruby' that achieve various things.

**Comment by morgvanny** [comment]
Yeah, the most interesting thing to me there is still slack-ruby-bot-server. I'd be all for using that unless we find a compelling reason not to
